/**
 * Markdown Report Generator.
 */

import type { ScanReport } from '../types/index.js';

export function generateMarkdownReport(report: ScanReport): string {
  const lines: string[] = [];

  lines.push(`# 🏷️ AXAG Scan Report`);
  lines.push('');
  lines.push(`**Target:** ${report.meta.target}  `);
  lines.push(`**Date:** ${report.meta.scannedAt}  `);
  lines.push(`**Domain:** ${report.meta.domain}  `);
  lines.push(`**Pages Scanned:** ${report.meta.pagesScanned}  `);
  lines.push(`**CLI Version:** ${report.meta.cliVersion}`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Elements Found | ${report.summary.totalElements} |`);
  lines.push(`| Annotations Generated | ${report.summary.annotated} |`);
  lines.push(`| Accepted | ${report.summary.accepted} |`);
  lines.push(`| Rejected | ${report.summary.rejected} |`);
  lines.push(`| Modified | ${report.summary.modified} |`);
  lines.push(`| Pending | ${report.summary.pending} |`);
  lines.push(`| Coverage | ${report.summary.coveragePercent}% |`);
  lines.push(`| Avg Confidence | ${report.summary.averageConfidence} |`);
  lines.push('');

  lines.push('## Pages Scanned');
  lines.push('');
  lines.push('| Page | Elements | Annotations |');
  lines.push('| --- | --- | --- |');
  for (const page of report.pages) {
    lines.push(`| ${page.title || page.url} | ${page.elementCount} | ${page.annotationCount} |`);
  }
  lines.push('');

  lines.push('## Annotations');
  lines.push('');

  for (const a of report.annotations) {
    const statusEmoji = a.status === 'accepted' ? '✅' : a.status === 'rejected' ? '❌' : a.status === 'modified' ? '✏️' : '⏳';
    lines.push(`### ${statusEmoji} \`${a.selector}\``);
    lines.push('');
    lines.push(`- **Intent:** \`${a.intent}\``);
    lines.push(`- **Entity:** \`${a.entity}\``);
    lines.push(`- **Action:** \`${a.actionType}\``);
    lines.push(`- **Risk:** \`${a.riskLevel}\``);
    lines.push(`- **Confidence:** ${Math.round(a.confidence * 100)}%`);
    lines.push(`- **Description:** ${a.description}`);
    lines.push(`- **Reasoning:** ${a.reasoning}`);
    lines.push('');

    if (a.requiredParameters.length > 0) {
      lines.push(`**Required params:** ${a.requiredParameters.map((p) => `\`${p}\``).join(', ')}`);
    }
    if (a.optionalParameters.length > 0) {
      lines.push(`**Optional params:** ${a.optionalParameters.map((p) => `\`${p}\``).join(', ')}`);
    }

    lines.push('');
    lines.push('```html');
    const tag = a.selector.match(/^(\w+)/)?.[1] || 'element';
    lines.push(`<${tag}`);
    for (const [key, value] of Object.entries(a.attributes)) {
      lines.push(`  ${key}="${value}"`);
    }
    lines.push(`>`);
    lines.push('```');
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push('## Risk Distribution');
  lines.push('');
  lines.push('| Risk Level | Count |');
  lines.push('| --- | --- |');
  for (const [level, count] of Object.entries(report.summary.riskDistribution)) {
    lines.push(`| ${level} | ${count} |`);
  }
  lines.push('');

  lines.push(`---`);
  lines.push(`*Generated by [axag-cli](https://axag.org) v${report.meta.cliVersion}*`);

  return lines.join('\n');
}
