import type { LintConfig } from '../types.js';

export const DEFAULT_CONFIG: LintConfig = {
  include: ['**/*.{html,htm,jsx,tsx}'],
  exclude: ['node_modules/**', 'dist/**', 'build/**'],
  rules: {
    'AXAG-LINT-001': 'error',
    'AXAG-LINT-002': 'error',
    'AXAG-LINT-003': 'error',
    'AXAG-LINT-004': 'error',
    'AXAG-LINT-005': 'error',
    'AXAG-LINT-006': 'warning',
    'AXAG-LINT-007': 'warning',
    'AXAG-LINT-008': 'error',
    'AXAG-LINT-009': 'error',
    'AXAG-LINT-010': 'warning',
    'AXAG-LINT-011': 'warning',
    'AXAG-LINT-012': 'error',
    'AXAG-LINT-013': 'error',
    'AXAG-LINT-014': 'warning',
    'AXAG-LINT-015': 'warning',
    'AXAG-LINT-016': 'warning',
    'AXAG-LINT-017': 'warning',
    'AXAG-LINT-018': 'warning',
    'AXAG-LINT-019': 'warning',
    'AXAG-LINT-020': 'warning',
    'AXAG-LINT-021': 'warning',
    'AXAG-LINT-022': 'warning',
    'AXAG-LINT-023': 'error',
    'AXAG-LINT-024': 'warning',
    'AXAG-LINT-025': 'info',
    'AXAG-LINT-026': 'warning',
    'AXAG-LINT-027': 'error',
    'AXAG-LINT-028': 'error',
  },
};
