/**
 * Bundler plugin — compiles annotations at build time and hands the results to
 * the app: JSON files in the build output, and a virtual module the runtime imports.
 *
 * Built on unplugin, so Vite, Rollup, webpack, Rspack and esbuild share one implementation.
 */

import path from 'node:path';
import { createUnplugin } from 'unplugin';
import type { UnpluginFactory } from 'unplugin';
import { compile, DEFAULT_EXCLUDE, DEFAULT_INCLUDE } from './index.js';
import type { CompileOptions, CompileResult } from './index.js';

export const VIRTUAL_TOOLS_ID = 'virtual:axag/tools';
const RESOLVED_VIRTUAL_TOOLS_ID = '\0' + VIRTUAL_TOOLS_ID;

export interface AxagPluginOptions extends Partial<CompileOptions> {
  /** Where the manifest is written in the build output. */
  manifestFileName?: string;
  /** Where the WebMCP tools are written; `false` to skip the file. */
  toolsFileName?: string | false;
  /** Fail the build when a diagnostic is an error (default true). */
  failOnError?: boolean;
  /** Called after every compile, including rebuilds in dev. */
  onCompile?: (result: CompileResult) => void;
}

const DEFAULT_MANIFEST = '.well-known/axag-manifest.json';
const DEFAULT_TOOLS = 'axag-tools.webmcp.json';

export const unpluginFactory: UnpluginFactory<AxagPluginOptions | undefined> = (rawOptions = {}) => {
  const options: AxagPluginOptions = { ...rawOptions };
  const manifestFileName = options.manifestFileName ?? DEFAULT_MANIFEST;
  const toolsFileName = options.toolsFileName === undefined ? DEFAULT_TOOLS : options.toolsFileName;
  const include = options.include ?? DEFAULT_INCLUDE;
  const exclude = options.exclude ?? DEFAULT_EXCLUDE;
  let root = path.resolve(options.root ?? process.cwd());
  let result: CompileResult | undefined;

  const run = async (): Promise<CompileResult> => {
    result = await compile({ ...options, root, include, exclude });
    options.onCompile?.(result);
    return result;
  };

  const virtualModule = (compiled: CompileResult): string =>
    [
      '// Generated by @axag/compiler. Import these where the agent runtime registers tools.',
      `export const tools = ${JSON.stringify(compiled.webmcpTools, null, 2)};`,
      `export const manifest = ${JSON.stringify(compiled.manifest, null, 2)};`,
      `export const dynamicActions = ${JSON.stringify(compiled.manifest.dynamic_actions ?? [])};`,
      'export default tools;',
    ].join('\n\n');

  return {
    name: '@axag/compiler',

    async buildStart() {
      const compiled = await run();
      const format = (diagnostic: CompileResult['diagnostics'][number]) =>
        `[axag] ${diagnostic.code} ${diagnostic.filePath ?? ''}:${diagnostic.line ?? 1} ${diagnostic.message}`;

      for (const diagnostic of compiled.diagnostics.filter(d => d.severity !== 'error')) {
        console.warn(format(diagnostic));
      }
      const errors = compiled.diagnostics.filter(d => d.severity === 'error');
      if (errors.length > 0) {
        // buildStart has no reporting context in unplugin, so failing means throwing.
        if (options.failOnError === false) errors.forEach(diagnostic => console.warn(format(diagnostic)));
        else throw new Error(errors.map(format).join('\n'));
      }
      if (compiled.manifest.actions.length === 0) {
        console.warn('[axag] No annotated elements found. Check the `include` option.');
      }
    },

    resolveId(id) {
      return id === VIRTUAL_TOOLS_ID ? RESOLVED_VIRTUAL_TOOLS_ID : undefined;
    },

    loadInclude(id) {
      return id === RESOLVED_VIRTUAL_TOOLS_ID;
    },

    async load(id) {
      if (id !== RESOLVED_VIRTUAL_TOOLS_ID) return undefined;
      return virtualModule(result ?? (await run()));
    },

    async buildEnd() {
      const compiled = result ?? (await run());
      this.emitFile({
        type: 'asset',
        fileName: manifestFileName,
        source: JSON.stringify(compiled.manifest, null, 2),
      });
      if (toolsFileName) {
        this.emitFile({
          type: 'asset',
          fileName: toolsFileName,
          source: JSON.stringify({ tools: compiled.webmcpTools }, null, 2),
        });
      }
    },

    vite: {
      configResolved(config: { root: string }) {
        if (!options.root) root = config.root;
      },
      /** Serve the manifest in dev, and recompile when an annotated file changes. */
      configureServer(server: {
        middlewares: { use: (handler: (req: { url?: string }, res: ServerResponse, next: () => void) => void) => void };
        watcher: { on: (event: string, listener: (file: string) => void) => void };
        moduleGraph: { getModuleById: (id: string) => unknown; invalidateModule: (module: never) => void };
        ws: { send: (payload: { type: string }) => void };
      }) {
        const paths = new Map<string, () => string>([
          ['/' + manifestFileName, () => JSON.stringify(result?.manifest ?? {}, null, 2)],
          ...(toolsFileName ? [['/' + toolsFileName, () => JSON.stringify({ tools: result?.webmcpTools ?? [] }, null, 2)] as const] : []),
        ]);

        server.middlewares.use((req, res, next) => {
          const body = req.url ? paths.get(req.url.split('?')[0])?.() : undefined;
          if (body === undefined) return next();
          res.setHeader('Content-Type', 'application/json');
          res.end(body);
        });

        const rebuild = async (file: string) => {
          if (!matches(file, root, include, exclude)) return;
          await run();
          const module = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_TOOLS_ID);
          if (module) {
            server.moduleGraph.invalidateModule(module as never);
            server.ws.send({ type: 'full-reload' });
          }
        };
        for (const event of ['add', 'change', 'unlink']) server.watcher.on(event, rebuild);
      },
    },
  };
};

interface ServerResponse {
  setHeader: (name: string, value: string) => void;
  end: (body: string) => void;
}

function matches(file: string, root: string, include: string[], exclude: string[]): boolean {
  const relative = path.relative(root, file);
  if (relative.startsWith('..')) return false;
  const extension = path.extname(file).toLowerCase();
  if (!['.html', '.htm', '.jsx', '.tsx', '.vue', '.ts', '.js'].includes(extension)) return false;
  return !exclude.some(pattern => minimatchLike(relative, pattern)) &&
    (include.some(pattern => minimatchLike(relative, pattern)) || ['.ts', '.js'].includes(extension));
}

/** Enough glob matching for watch filtering: `**` and `*` and `{a,b}` alternatives. */
function minimatchLike(value: string, pattern: string): boolean {
  const expanded = pattern.replace(/\{([^}]+)\}/g, (_match, group: string) => `(${group.split(',').join('|')})`);
  const regex = new RegExp(
    '^' +
      expanded
        .replace(/[.+^$()|[\]\\]/g, '\\$&')
        .replace(/\*\*\//g, '(.*/)?')
        .replace(/\*\*/g, '.*')
        .replace(/\*/g, '[^/]*') +
      '$',
  );
  return regex.test(value);
}

export const unplugin = /* @__PURE__ */ createUnplugin(unpluginFactory);
export default unplugin;
